services:
  - type: web
    name: figmaapi-ml-service
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3002
    disk:
      name: ml-models
      mountPath: /opt/render/project/src/models
      sizeGB: 1 